"""add gender to person

Revision ID: ad7fcb32c47d
Revises: 404139762fd2
Create Date: 2020-09-13 10:15:21.403213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7fcb32c47d'
down_revision = '404139762fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('gender', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'gender')
    # ### end Alembic commands ###
